# fly.toml app configuration file generated for reactivities-course-jc on 2023-11-26T12:53:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities-course-jc"
primary_region = "dfw"

[build]
  image = "jcasarez3/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dipntaqd7"
  Cloudinary__ApiKey="375169787994679"
  Facebook__AppId="670686851855368"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
